_extends: .github

repository:
  name: rxpy
  description:  A fast (experimental) RX algorithm implementation in Python 3.9+
  homepage: https://github.com/bjd2385/rxpy

  # A comma-separated list of topics to set on the repository
  topics: rx, algorithm, mahalanobis, image
  private: false