version: 2.1


setup: true


orbs:
  dynamic: bjd2385/dynamic-continuation@3.6.12
  general: bjd2385/general@0.7.5
  slack: circleci/slack@4.12.5


workflows:
  rxpy:
    jobs:
      - dynamic/continue:
          context: orb-publishing

      - slack/on-hold:
          context: slack
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v?[0-9]+\.[0-9]+\.[0-9]+$/

      - request-approval:
          requires:
            - slack/on-hold
          type: approval
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v?[0-9]+\.[0-9]+\.[0-9]+$/

      - general/github-release:
          name: Create GitHub release from tag
          context: github
          requires:
            - request-approval
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v?[0-9]+\.[0-9]+\.[0-9]+$/

      - general/python-release-poetry:
          name: pypi upload [python]
          context: pypi
          username: $PYPI_USERNAME
          password: $API_TOKEN
          repository: python
          requires:
            - request-approval
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v?[0-9]+\.[0-9]+\.[0-9]+$/